### ISSUE TITLE
server.py is very sensible to path's format

### ISSUE THREAD

**Issue by Polochon-street** [Phyks/Blissify#3]
Hi,

Server.py crashed when I tried to do <code>python ./server.py --full-rescan /home/polochon/Musique/MPD</code> because I omitted the trailing slash; /home/polochon/Musique/MPD/ worked, though.

Just thought it would be cool to report - the database is being built as I speak :p

Thanks!

**Comment by Phyks** [comment]
Should be fixed by https://github.com/Phyks/Blissify/commit/adabeffa7f4501676e8a3cc05a96ab1814993ab7.
