### ISSUE TITLE
Missing fftw3 dependency on Debian Jessie

### ISSUE THREAD

**Issue by FelixDefrance** [Phyks/Blissify#9]
Hi guys, 

I don't find the right package to satisfy fttw3 dependency. Anybody have same issue ? 

```
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie
```

```
~/blissify/build# cmake ..
```
```
-- checking for modules 'libavformat;libavutil;libavcodec;fftw3'
--   package 'fftw3' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  bliss/CMakeLists.txt:7 (pkg_check_modules)


-- checking for modules 'libavformat;libavutil;libavcodec;fftw3'
--   package 'fftw3' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:10 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/root/blissify/build/CMakeFiles/CMakeOutput.log".
```
```
~/blissify/build# apt-cache search fftw
```
```
cl-fftw3 - Common Lisp package for using the FFTW3 library
fftw-dev - library for computing Fast Fourier Transforms
fftw-docs - documentation for fftw
fftw2 - library for computing Fast Fourier Transforms
sfftw-dev - library for computing Fast Fourier Transforms
sfftw2 - library for computing Fast Fourier Transforms
libfftw3-3 - Library for computing Fast Fourier Transforms
libfftw3-bin - Library for computing Fast Fourier Transforms - Tools
libfftw3-dbg - Library for computing Fast Fourier Transforms - debug symbols
libfftw3-dev - Library for computing Fast Fourier Transforms - development
libfftw3-doc - Documentation for fftw version 3
libfftw3-double3 - Library for computing Fast Fourier Transforms - Double precision
libfftw3-long3 - Library for computing Fast Fourier Transforms - Long precision
libfftw3-mpi-dev - MPI Library for computing Fast Fourier Transforms - development
libfftw3-mpi3 - MPI Library for computing Fast Fourier Transforms
libfftw3-single3 - Library for computing Fast Fourier Transforms - Single precision
mffm-fftw-dev - A C++ wrapper for the fftw.org C library (version 3)
mffm-fftw1 - A C++ wrapper for the fftw.org C library (version 3)
pd-bsaylor - library of FFT-based Pd objects by Ben Saylor
python-fftw - Python bindings to the FFTW3 C-library for Fourier transforms
root-plugin-math-fftw3 - FFTw plugin for ROOT
ruby-fftw3 - Ruby interface to the FFTW Ver.3 library
ruby-fftw3-dbg - Ruby FFT library using FFTW Ver.3
sndfile-tools - Collection of programs for operating on sound files
yorick-yeti-fftw - FFT plugin for the Yorick language
yorick-ynfft - nonequispaced fast Fourier transform for Yorick
```

Thx

**Comment by Phyks** [comment]
Hi,

Should be `libfftw3-dev` I think, although I cannot confirm at 100% because I do not have a Debian Jessie system at hand.

**Comment by FelixDefrance** [comment]
Yes, that right!

But now compilation failed :(

```
~/blissify/build# make
[  7%] Building C object bliss/CMakeFiles/bliss.dir/src/amplitude_sort.c.o
In file included from /root/blissify/bliss/src/amplitude_sort.c:1:0:
/root/blissify/bliss/include/bliss.h:6:35: fatal error: libswresample/version.h: No such file or directory
 #include <libswresample/version.h>
                                   ^
compilation terminated.
bliss/CMakeFiles/bliss.dir/build.make:54: recipe for target 'bliss/CMakeFiles/bliss.dir/src/amplitude_sort.c.o' failed
make[2]: *** [bliss/CMakeFiles/bliss.dir/src/amplitude_sort.c.o] Error 1
CMakeFiles/Makefile2:154: recipe for target 'bliss/CMakeFiles/bliss.dir/all' failed
make[1]: *** [bliss/CMakeFiles/bliss.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```
```
~/blissify/build# dpkg -l | grep bliss
ii  bliss-music                        1.0                               all          A music analyzis library
```
Any idea ? 
Thx

**Comment by Phyks** [comment]
It seems you installed `bliss` with your package manager already. `Blissify` currently ships with its own copy of `bliss` as a Git submodule, and tries to build it.

I am not sure what is included in the `bliss` package for Debian (ping @PolochonStreet who might know much about this), but you might sort things out by commenting out [this line](https://github.com/Phyks/Blissify/blob/master/CMakeLists.txt#L5) and building again.

If you follow the installation procedure in the `README.md` of this project, it will build its own version of `bliss` and then you should have a look at [the required dependencies for Bliss](https://github.com/Polochon-street/bliss#dependencies).

**Comment by Polochon-street** [comment]
Hi, 
After investigating a bit, for some reason you should replace
"
pkg_check_modules(RESAMPLE QUIET libswresample)

if(NOT RESAMPLE_FOUND)
    pkg_check_modules(RESAMPLE REQUIRED libavresample)
    set(AVRESAMPLE TRUE)
else()
    set(AVRESAMPLE FALSE)
endif()
"

by
pkg_check_modules(RESAMPLE  libavresample)

and it should work.
The libav is failing, I don't know why but the problem's on bliss so I'll try to solve this.

**Comment by Polochon-street** [comment]
Hi,
You should recompile Bliss yourself: if you could install libswresample-dev in jessie-backports instead of libavresample-dev (which is barely maintained anymore), I think this would solve your problem.

However, it is not normal that the libavresample doesn't work, so I'll investigate.

**Comment by FelixDefrance** [comment]
Hi, 

I don't need to rebuild bliss. Just add deps from backports, like you said.

`apt-get install -t jessie-backports libswresample-dev  libavutil-dev`

Another dependence is needed to satify compilation
`apt-get install libsqlite3-dev`

Now, i'm facing a new issue. --listen don't work. I had to install python3-dateutil to solve is :
```
~/blissify/mpd# ./server.py --listen
Traceback (most recent call last):
  File "./server.py", line 10, in <module>
    import dateutil.parser
ImportError: No module named 'dateutil'
```

And after, I stack in this:  (python-mpdclient and python-mpd doesn't solve the problem) 
```
./server.py --listen
Traceback (most recent call last):
  File "./server.py", line 17, in <module>
    from mpd import MPDClient
```

Thx

**Comment by FelixDefrance** [comment]
ok python-mpd2 !
But it doesn't provided by Debian. Even in experimental branch..

https://packages.debian.org/search?suite=experimental&searchon=names&keywords=python-mpd2

So, python-mpd2 is it really needed ?

**Comment by Phyks** [comment]
These are specified in the `requirements.txt` file (https://github.com/Phyks/Blissify/blob/master/mpd/requirements.txt). Concerning why `python-mpd2`, the other ones are outdated and this one is the best choice for a new project. See [this part of their README](https://github.com/Mic92/python-mpd2#difference-with-python-mpd).
